laravel/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('site', function(){
		return view('layouts.app');
	});
Route::group(['middleware' => ['web']], function(){
	//slug
	Route::get('blog/{slug}', ['uses' => 'blogController@getSingle', 'as' => 'blog.single'])->where('slug','[\w\d\-\_]+');
	//categories
	Route::resource('categories', 'categoryController', ['except' => ['create', 'show', 'destroy']]);
	//tags
	Route::resource('tags', 'tagController', ['except' => ['create']]);
	//comments
	Route::post('comments/{post_id}', ['uses' => 'commentsController@store', 'as' => 'comments.store']);
	Route::get('comments/{id}/edit', ['uses' => 'commentsController@edit', 'as' => 'comments.edit']);
	Route::put('comments/{id}', ['uses' => 'commentsController@update', 'as' => 'comments.update']);
	Route::delete('comments/{id}', ['uses' => 'commentsController@destroy', 'as' => 'comments.destroy']);
	Route::get('comments/{id}', ['uses' => 'commentsController@delete', 'as' => 'comments.delete']);
	//pages
	Route::get('blog', ['uses' => 'blogController@getIndex', 'as' => 'blog.index']);
	Route::get('about', 'pageController@about');
	Route::get('contact', 'pageController@contact');
	Route::get('welcome', 'pageController@index');
	Route::post('contact', 'pageController@postContact');
	//posts
	Route::resource('posts','postController');
	
});
//test route

Route::get('test','TestController@index');

//phpinfo

Route::get('phpinfo', function(){
	phpinfo();
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

laravel/resources/views/partials/_css.blade.php
<!-- Bootstrap core CSS -->
	{{ Html::style('css/bootstrap.css')}}
	{{ Html::style('css/styles.css') }}
	{{ Html::style('css/all.css') }}
    <!-- Custom styles for this template -->
    <link href="../css/jumbotron.css" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="../css/parsley.css">

laravel/resources/views/partials/_homenav.blade.php
<div class="container">
      <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
        <a class="navbar-brand" href="#">My Blog</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarsExample09">
          <ul class="navbar-nav mr-auto">
            <li class="{{ Request::is('welcome') ? "active" : ""}}">
              <a class="nav-link" href="/welcome">Home</a>
            </li>
            <li class="{{ Request::is('blog') ? "active" : ""}}">
              <a class="nav-link" href="/blog">Blog</a>
            </li>
            <li class="{{ Request::is('about') ? "active" : ""}}">
              <a class="nav-link" href="/about">About Us</a>
            </li>
            <li class="{{ Request::is('contact') ? "active" : ""}}">
              <a class="nav-link" href="/contact">Contact Us</a>
            </li>
            @guest
              <a href="#"></a>
            @else
            <li class="{{ Request::is('posts/create') ? "active" : ""}}">
              <a class = "nav-link" href="{{ route('posts.create') }}">Create Post</a>
            </li>
            @endguest
          </ul>
          <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
            @guest
                <li><a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a></li>
                <li><a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a></li>
            @else
                <li class="nav-item dropdown">
                    <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>Hello
                        {{ Auth::user()->name }} <span class="caret"></span>
                    </a>
                    <div class="dropdown-menu">
                     <a class = "dropdown-item" href="{{ route('posts.index') }}">Post</a>
                     <a class="dropdown-item" href="{{ route('categories.index') }}">Categories</a>
                     <a class="dropdown-item" href="{{ route('tags.index') }}">Tags</a>
                      <a class="dropdown-item" href="{{ route('logout') }}"
                           onclick="event.preventDefault();
                                         document.getElementById('logout-form').submit();">
                            {{ __('Logout') }}
                      </a>
                        <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                            @csrf
                        </form>
                    </div>
                </li>         
            @endguest
          </ul>
        </div>
      </nav>
</div>

laravel/resources/views/partials/_js.blade.php
{{ Html::script('js/jquery-3.3.1.js') }}
{{ Html::script('js/app.js') }}
{{ Html::script('js/bootstrap.js') }}
{{ Html::script('js/scri.js') }}
{{ Html::script('js/all.js') }}
<script type = 'text/javascript' src = 'js/parsley.min.js'>

laravel/resources/views/partials/_messages.blade.php
<div class="col-md-6 offset-3">
	@if (Session::has('success'))
		<div class="alert alert-success alert-dismissible fade show" role = "alert">
			<strong>Success: </strong>{{ Session::get('success')}}
			<button type="button" class="close" data-dismiss="alert" aria-label="Close">
				<span aria-hidden="true">&times;</span>
			</button>
		</div>
	@endif
	@if(count($errors)>0)
		<div class="alert alert-danger alert-dismissible fade show" role = "alert">
			<strong>Errors:</strong>
			<ul>
				@foreach($errors->all() as $error)
				<li>{{ $error}}</li>
				@endforeach
			</ul>
			<button type="button" class="close" data-dismiss="alert" aria-label="Close">
				<span aria-hidden="true">&times;</span>
			</button>
		</div>
	@endif
</div>