laravel/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('site', function(){
		return view('layouts.app');
	});
Route::group(['middleware' => ['web']], function(){
	//slug
	Route::get('blog/{slug}', ['uses' => 'blogController@getSingle', 'as' => 'blog.single'])->where('slug','[\w\d\-\_]+');
	//categories
	Route::resource('categories', 'categoryController', ['except' => ['create', 'show', 'destroy']]);
	//tags
	Route::resource('tags', 'tagController', ['except' => ['create']]);
	//comments
	Route::post('comments/{post_id}', ['uses' => 'commentsController@store', 'as' => 'comments.store']);
	Route::get('comments/{id}/edit', ['uses' => 'commentsController@edit', 'as' => 'comments.edit']);
	Route::put('comments/{id}', ['uses' => 'commentsController@update', 'as' => 'comments.update']);
	Route::delete('comments/{id}', ['uses' => 'commentsController@destroy', 'as' => 'comments.destroy']);
	Route::get('comments/{id}', ['uses' => 'commentsController@delete', 'as' => 'comments.delete']);
	//pages
	Route::get('blog', ['uses' => 'blogController@getIndex', 'as' => 'blog.index']);
	Route::get('about', 'pageController@about');
	Route::get('contact', 'pageController@contact');
	Route::get('welcome', 'pageController@index');
	Route::post('contact', 'pageController@postContact');
	//posts
	Route::resource('posts','postController');
	
});
//test route

Route::get('test','TestController@index');

//phpinfo

Route::get('phpinfo', function(){
	phpinfo();
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

laravel/app/Tag.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Tag extends Model
{
    public function posts()
    {
    	return $this->belongsToMany('App\Post');
    }
}

laravel/app/Http/Controllers/tagController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Tag;
use Session;

class tagController extends Controller
{

    public function __construct()
    {
        $this->middleware('auth');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $tags = Tag::all();

        return view('tags.index')->withTags($tags);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, array(
            'name' => 'required|max:255',
        ));

        $tags = new Tag;
        $tags->name = $request->name;
        $tags->save();

        Session::flash('success', 'Tag successfully created!');

        return redirect()->route('tags.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $tags = Tag::find($id);

        return view('tags.show')->withTags($tags);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $tags = Tag::find($id);

        return view('tags.edit')->withTags($tags);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $tags = Tag::find($id);

        $this->validate($request, ['name' => 'required|max:255']);

        $tags->name = $request->input('name');

        $tags->save();

        Session::flash('success', 'Tag successfully updated!');

        return redirect()->route('tags.show', $tags->id);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $tags = Tag::find($id);

        $tags->posts()->detach();

        $tags->delete();

        Session::flash('success', 'Tag successfully deleted!');

        return redirect()->route('tags.index');
    }
}

laravel/resources/views/tags/edit.blade.php
@extends('blog.main')

@section('title', 'Edit Tag')

@section('content')

	<h3>Edit {{ $tags->name }} Tag</h3>
	<hr>
	<div class="container">
		<div class="row">
			<div class="col-md-8 offset-2">
				{!! Form::model($tags, ['route' => ['tags.update', $tags->id], 'method' => 'PUT']) !!}
					{{ Form::label('name', 'Name:') }}
					{{ Form::text('name', null, ['class' => 'form-control']) }}
					{{ Form::submit('Edit Tag', ['class' => 'btn btn-success btn-lg']) }}
				{!! Form::close() !!}
			</div>
		</div>
	</div>

@endsection

laravel/resources/views/tags/index.blade.php
@extends('blog.main')

@section('title', '| Create New Tags')

@section('content')

	<div class="row">
		<div class="col-md-7 offset-1">
			<h1>Tags</h1>
			<table class="table table-hover table-responsive-md">
				<thread>
					<tr>
						<th>#</th>
						<th>Name</th>
					</tr>
				</thread>
				@foreach($tags as $tag)
					<tbody>
						<tr>
							<th>{{ $tag->id }}</th>
							<td><a href="{{ route('tags.show', $tag->id) }}">{{ $tag->name }}</a></td>
						</tr>
					</tbody>

				@endforeach
			</table>
		</div><!--end col-md-8 -->
		<div class="col-md-3">
			<div class="card card-body bg-light">
				{!! Form::open(['route' => 'tags.store', 'method' => 'POST']) !!}
					<h2>Create Tag</h2>
					{{ Form::label('name', 'Name:') }}
					{{ Form::text('name', null, ['class' => 'form-control']) }}
					{{ Form::submit('Create New Tag', ['class' => 'btn btn-primary btn-block', 'style' => 'margin-top:10px;']) }}
				{!! Form::close() !!}
			</div>
		</div>
	</div><!--end of row>

@endsection

laravel/resources/views/tags/show.blade.php
@extends('blog.main')

<?php $titletag = stripslashes($tags->name) ?>

@section('title', "| $titletag Tag")

@section('content')
	<div class="container">
	<div class="row">
		<div class="col-md-8">
			<h3>{{ $tags->name }} Tag <small>{{ $tags->posts()->count() }} Posts</small></h3>
		</div>
		<div class="col-md-2">
			<a href="{{ route('tags.edit', $tags->id) }}" class="btn btn-primary btn-block">Edit</a>
		</div>
		<div class="col-md-2">
			{!! Form::open(['route' => ['tags.destroy', $tags->id], 'method' => 'DELETE']) !!}
				{{ Form::submit('Delete', ['class' => 'btn btn-danger btn-block']) }}
			{!! Form::close() !!}
		</div>
	</div>
	<hr>
	<div class="row">
		<div class="col-md-12">
			<table class="table table-hover table-responsive-md">
				<thead>
					<th>#</th>
					<th>Title</th>
					<th>Tags</th>
					<th></th>
				</thead>
				<tbody>
					@foreach($tags->posts as $post)
						<tr>
							<th>{{ $post->id }}</th>
							<td>{{ $post->title }}</td>
							<td>@foreach($post->tags as $tag)
									<span class="badge badge-secondary">{{ $tag->name }}</span>
								@endforeach
							</td>
							<td><a href="{{ route('posts.show', $post->id) }}" class="btn btn-outline-secondary btn-sm">View</a></td>
						</tr>
					@endforeach
				</tbody>
			</table>
		</div>
	</div>
</div>
@endsection